name: Task (Non-Technical)
description: (Non-Technical) Standard Dalmatian Development issue
title: "[BRIEF DESCRIPTION]"
labels: ["needs-triage"]
body:
  - type: textarea
    id: request
    attributes:
      label: Feature Request or Bug Report
      description: What is this issue trying to accomplish and why? If applicable where does the project stand right now?
      placeholder: "e.g. The transition between the about and help page stutters randomly. Fix this bug if possible."
    validations:
      required: true

  - type: textarea
    id: contacts
    attributes:
      label: Points of Contact
      description: Add who to ask questions regarding this issue, if able. Otherwise keep default contacts.
      value: |
        - @Tentype — technical issues/help and outreach/usage
        - @maybe-yiyi — technical issues/help
        - @Gostmeaper - outreach and product usage
